services:
  bot:
    build: .
    container_name: joyreactor-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:16
    container_name: joyreactor-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: joyreactor_data
      POSTGRES_USER: saitama
      POSTGRES_PASSWORD: hungry
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: joyreactor-redis
    restart: unless-stopped
    ports:
      - "6739:6739"
    volumes:
      - redis_data:/data

volumes:
  postgres-data:
  redis_data:



